apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-service
  template:
    metadata:
      labels:
        app: alert-service
    spec:
      containers:
      - name: alert-service
        image: myregistry/alert-service:latest
        env:
        - name: KAFKA_BROKER
          value: "kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: alert-service
spec:
  selector:
    app: alert-service
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: alert-route
spec:
  to:
    kind: Service
    name: alert-service
  port:
    targetPort: 5000
